# Generated by Django 6.0.4 on 2026-04-25 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_virtualcard_zero_starting_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualcard',
            options={'ordering': ('created_at',)},
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='name',
            field=models.CharField(default='Asosiy karta', max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualcard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
