# Generated by Django 6.0.4 on 2026-04-25 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ('username',), 'verbose_name': 'Custom user', 'verbose_name_plural': 'Custom users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, help_text='Enter phone number in international format.', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must contain 9 to 15 digits and may start with '+'.", regex='^\\+?\\d{9,15}$')]),
        ),
    ]
